# Generated by Django 5.0 on 2025-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_path', models.CharField(help_text='Path to the saved snapshot image.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(default='fight', max_length=50)),
            ],
            options={
                'db_table': 'violence_events',
            },
        ),
    ]
