# Generated by Django 5.0 on 2025-10-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_path', models.CharField(help_text='Path to the saved snapshot image.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed - Valid'), ('FALSE', 'False Alarm')], default='NEW', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ViolenceEvent',
        ),
    ]
