# Generated by Django 5.0 on 2025-10-10 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_app', '0002_weaponevent_delete_violenceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEvidence',
            fields=[
                ('evidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='URL path to the stored snapshot image.', max_length=255)),
                ('file_type', models.CharField(default='image/jpeg', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_value', models.FloatField(help_text='Confidence score (for WEAPON) or count (for OVERCROWDING).')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed - Valid'), ('FALSE', 'False Alarm'), ('CLOSED', 'Closed')], default='NEW', help_text='Current status of the incident for review.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Alert name (WEAPON, INTRUSION, OVERCROWDING, UOD)', max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceArea',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('overcrowding_threshold', models.IntegerField(default=5, help_text='Maximum people allowed in this zone.')),
                ('is_active', models.BooleanField(default=True, help_text='Is this area actively being monitored?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceCoordinate',
            fields=[
                ('coord_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='surveillance_app.surveillancearea')),
            ],
            options={
                'verbose_name_plural': 'Surveillance Coordinates',
                'ordering': ['coord_id'],
            },
        ),
        migrations.CreateModel(
            name='TrackedObject',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('tracker_id', models.IntegerField(help_text='Unique ID assigned by the YOLO tracker.')),
                ('class_name', models.CharField(help_text='Detected class (e.g., backpack, suitcase).', max_length=50)),
                ('abandonment_duration', models.FloatField(help_text='Time object was stationary (seconds).')),
                ('initial_coords', models.CharField(help_text='Start position of the object (bbox center).', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='WeaponEvent',
        ),
        migrations.AddField(
            model_name='eventevidence',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='surveillance_app.eventlog'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveillance_app.eventtype'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='area',
            field=models.ForeignKey(blank=True, help_text='The area where the intrusion/overcrowding occurred.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveillance_app.surveillancearea'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='object_details',
            field=models.ForeignKey(blank=True, help_text='Details for UOD events.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveillance_app.trackedobject'),
        ),
    ]
