# Generated by Django 5.0 on 2025-10-20 15:51

import django.db.models.deletion
from django.db import migrations, models


def migrate_eventtype_codes(apps, schema_editor):
    EventType = apps.get_model('surveillance_app', 'EventType')
    for et in EventType.objects.all():
        if et.name == 'OVERCROWDING':
            et.code = 'CROWD'
        else:
            et.code = et.name
        et.save()


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_app', '0003_eventevidence_eventlog_eventtype_surveillancearea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='area',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='object_details',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='type',
        ),
        migrations.RemoveField(
            model_name='surveillancecoordinate',
            name='area',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='type_id',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='surveillancearea',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='surveillancearea',
            name='overcrowding_threshold',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='auto_escalate',
            field=models.BooleanField(default=False, help_text='Should this event automatically trigger an alert?'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='code',
            field=models.CharField(choices=[('WEAPON', 'Weapon Detection'), ('CROWD', 'Overcrowding'), ('UOD', 'Unattended Object Detection'), ('INTRUSION', 'Suspicious Movement / Intrusion')], help_text='Short code for the event type.', max_length=10, null=True, blank=True),
        ),
        migrations.RunPython(migrate_eventtype_codes),
        migrations.AlterField(
            model_name='eventtype',
            name='code',
            field=models.CharField(choices=[('WEAPON', 'Weapon Detection'), ('CROWD', 'Overcrowding'), ('UOD', 'Unattended Object Detection'), ('INTRUSION', 'Suspicious Movement / Intrusion')], help_text='Short code for the event type.', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='priority',
            field=models.IntegerField(default=5, help_text='Priority level (1=High, 10=Low).'),
        ),
        migrations.AddField(
            model_name='surveillancearea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveillancearea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(help_text='Full name of the event type.', max_length=100),
        ),
        migrations.AlterField(
            model_name='surveillancearea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='surveillancearea',
            name='name',
            field=models.CharField(help_text='Human-readable name for the area.', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(help_text='Unique hardware identifier for the camera.', max_length=50, unique=True)),
                ('location_description', models.CharField(help_text="E.g., 'West wall, facing entrance'.", max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='surveillance_app.surveillancearea')),
            ],
        ),
        migrations.CreateModel(
            name='AreaObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='NEW', max_length=20)),
                ('analyst_notes', models.TextField(blank=True, null=True)),
                ('resolution_time', models.DateTimeField(blank=True, null=True)),
                ('evidence_path', models.CharField(help_text='Path or URL to the digital evidence (snapshot/video clip).', max_length=255)),
                ('event_type', models.ForeignKey(limit_choices_to={'code__in': ['UOD', 'INTRUSION']}, on_delete=django.db.models.deletion.PROTECT, to='surveillance_app.eventtype')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_observations', to='surveillance_app.camera')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_confidence', models.FloatField(blank=True, help_text='Confidence score of the UOD detection.', null=True)),
                ('bounding_box', models.JSONField(blank=True, help_text='JSON array for bounding box coordinates [x1, y1, x2, y2].', null=True)),
                ('movement_path', models.JSONField(blank=True, help_text='JSON list of coordinates/timestamps for tracking.', null=True)),
                ('is_human', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField(default=0, help_text='How long the object was unattended or the movement lasted.')),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='surveillance_app.areaobservation')),
            ],
        ),
        migrations.DeleteModel(
            name='EventEvidence',
        ),
        migrations.DeleteModel(
            name='TrackedObject',
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
        migrations.DeleteModel(
            name='SurveillanceCoordinate',
        ),
    ]
